version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: npm run serve
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    volumes:
      - ./backend:/code
      - save-data:/dist/save
    ports:
      - "5001:5001"
    environment:
      - UseRobots=false

volumes:
  save-data: