name: Docker Images CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1'
    steps:
    - uses: actions/checkout@v2
    - name: Build the Unified Docker image
      run: docker build . --file Dockerfile --tag albertoxamin/bang:latest
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push images
      run: docker push albertoxamin/bang:latest
