name: Docker Images CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Backend Docker image
      run: cd backend;docker build . --file Dockerfile --tag albertoxamin/bang-backend:latest
    - uses: actions/checkout@v2
    - name: Build the Frontend Docker image
      run: cd frontend;docker build . --file Dockerfile --tag albertoxamin/bang-frontend:latest
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push iamges
      run: docker push albertoxamin/bang-backend:latest; docker push albertoxamin/bang-frontend:latest
